name: ie-bank-backend

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  BACKEND_WEBAPP_DEV: glerer-be-dev #CAMBIAR ESTO PARA DEPLOY A MI PROPIO WORKFLOW. EXTRA: usar application insight to monitor appliations. 
  BACKEND_WEBAPP_UAT: glerer-be-uat

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ghci
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        working-directory: ./backend
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend
      - name: Lint with flake8
        run: |
          pip install flake8 pytest
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        working-directory: ./backend
      - name: Test with pytest
        run: python -m pytest --cov=iebank_api -v
        working-directory: ./backend
      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: ./backend

  deploy-dev:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Web App (Backend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.BACKEND_WEBAPP_DEV }}
          package: ./

  backend-deploy-uat:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Web App (Backend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.BACKEND_WEBAPP_UAT }}
          package: ./